global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'gateway'
    static_configs:
      - targets: ['gateway:8080']
    metrics_path: /metrics
    scrape_interval: 10s

  - job_name: 'auth'
    static_configs:
      - targets: ['auth:5000']
    metrics_path: /metrics
    scrape_interval: 10s

  - job_name: 'notifier'
    static_configs:
      - targets: ['notifier:5001']
    metrics_path: /metrics
    scrape_interval: 10s

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
